color0 #514533
color1 #ffb4ab
color2 #ffd793
color3 #e8c17f
color4 #d0e85a
color5 #ffba27
color6 #e8c17f
color7 #ede1d1
color8 #9e8f79
color9 #ffb4ab
color10 #ffd793
color11 #e8c17f
color12 #d0e85a
color13 #ffba27
color14 #e8c17f
color15 #ede1d1

cursor                #ede1d1
cursor_text_color     #181309
background            #181309
foreground            #ede1d1
selection_foreground  #d5c4ac
selection_background  #514533
active_border_color   #ffd793
inactive_border_color #514533
url_color             #ffd793

active_tab_foreground   #422d00
active_tab_background   #ffd793
inactive_tab_foreground #d5c4ac
inactive_tab_background #514533
cursor_trail_color      #d5c4ac
